server:
  port: 10000

#MyBatis
log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@//localhost:1521/XE
      username: hr
      password: hr

#  servlet:
#    multipart:
#      location: C:/upload
#      max-request-size: 40MB
#      max-file-size: 40MB
#      file-size-threshold: 100MB
#    session:
#      timeout: 1800


spring.mvc.static-path-pattern: /static/**